FROM micropython/build-micropython-unix

WORKDIR /

# Clone MicroPython
RUN git config --global http.sslVerify false
RUN git clone --recursive https://github.com/micropython/micropython.git

#Build MicroPython
WORKDIR /micropython
RUN make -C mpy-cross && make -C ports/unix submodules all -j4


# Set the default shell to bash
SHELL ["/bin/bash", "-c"]

# Keep the container running with an interactive shell
CMD ["/bin/bash"]
